### ISSUE TITLE
Admin Extension Error

### ISSUE THREAD

**Issue by MegabotLA** [Zalatis/LostArkDiscordBot#1]
Starting to load cogs...
Extension activities loaded.
Failed to load extension admin: Extension 'bot.cogs.admin' raised an error: AttributeError: module 'discord.commands.permissions' has no attribute 'has_any_role'

Any Idea?

**Comment by Zalatis** [comment]
Can you do 
`pip freeze`
in a terminal and show me the result ?
It may be because you also have discord.py installed

**Comment by MegabotLA** [comment]
Yes i have uninstalled discord.py now it shows me up i need a module named     from .enums import ButtonStyle, ComponentType, InputTextStyle, try_enum
ModuleNotFoundError: No module named 'discord.enums'

**Comment by Zalatis** [comment]
Well if you still have errors concerning module discord, you may not installed py-cord correctly.

Show me the result of 
`pip freeze`

**Comment by MegabotLA** [comment]
aiohttp==3.7.4.post0
altgraph==0.17.2
appdirs==1.4.4
async-generator==1.10
async-timeout==3.0.1
attrs==21.4.0
auto-py-to-exe==2.18.0
bcrypt==3.2.0
beautifulsoup4==4.11.1
bottle==0.12.19
bottle-websocket==0.2.9
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.0
chardet==4.0.0
charset-normalizer==2.0.6
click==7.1.2
colorama==0.4.4
configparser==5.2.0
crayons==0.4.0
cryptography==36.0.1
cycler==0.11.0
Cython==0.29.28
decompyle3==3.8.0
distlib==0.3.4
docutils==0.17.1
Eel==0.12.4
filelock==3.6.0
fonttools==4.29.1
future==0.18.2
gevent==21.12.0
gevent-websocket==0.10.1
google==3.0.0
google-api-core==2.7.3
google-auth==2.6.6
google-cloud-core==2.3.0
google-cloud-firestore==2.4.0
googleapis-common-protos==1.56.0
greenlet==1.1.2
grpcio==1.46.0
grpcio-status==1.46.0
h11==0.13.0
idna==3.2
keyboard==0.13.5
Kivy==2.0.0
kivy-deps.angle==0.3.0
kivy-deps.glew==0.3.0
kivy-deps.sdl2==0.3.1
Kivy-Garden==0.1.4
kivymd==0.104.2
kiwisolver==1.3.2
llvmlite==0.38.0
Mako==1.2.0
MarkupSafe==2.1.1
matplotlib==3.5.1
MouseInfo==0.1.3
mss==6.1.0
multidict==6.0.2
mysql==0.0.3
mysql-connector==2.2.9
mysqlclient==2.1.0
Nuitka==0.7.7
numba==0.55.1
numpy==1.21.6
opencv-python==4.5.3.56
outcome==1.1.0
packaging==21.3
pefile==2021.9.3
Pillow==9.0.1
pipenv==2022.4.21
platformdirs==2.5.2
playsound==1.3.0
prettytable==3.1.1
proto-plus==1.20.3
protobuf==3.20.1
psutil==5.8.0
py-cord==2.0.0b7
pyarmor==7.4.1
pyarmor-webui==1.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAutoGUI==0.9.53
pycdas==1.2.1
pycparser==2.21
PyDirectInput==1.0.4
PyGetWindow==0.0.9
Pygments==2.10.0
pygubu==0.20
pygubu-designer==0.24
pyinstaller==4.10
pyinstaller-hooks-contrib==2022.2
PyJWT==2.3.0
PyMsgBox==1.0.9
PyNaCl==1.5.0
pynput==1.7.6
pyOpenSSL==22.0.0
pyparsing==3.0.7
pyperclip==1.8.2
pypiwin32==223
PyQt5==5.15.4
pyqt5-plugins==5.15.4.2.2
PyQt5-Qt5==5.15.2
PyQt5-sip==12.9.1
pyqt5-tools==5.15.4.3.2
PyRect==0.1.4
PyScreeze==0.1.28
PySide6==6.3.0
PySide6-Addons==6.3.0
PySide6-Essentials==6.3.0
PySocks==1.7.1
pytesseract==0.3.9
python-dateutil==2.8.2
python-dotenv==0.20.0
pytweening==1.0.4
pytz==2021.3
pywin32==301
pywin32-ctypes==0.2.0
PyYAML==6.0
qt5-applications==5.15.2.2.2
qt5-tools==5.15.2.1.2
requests==2.26.0
rsa==4.8
screen-search==1.0
selenium==4.1.2
shiboken6==6.3.0
six==1.16.0
slugify==0.0.1
sniffio==1.2.0
sortedcontainers==2.4.0
soupsieve==2.3.2.post1
spark-parser==1.8.9
spotipy==2.19.0
tk==0.1.0
transitions==0.8.11
trio==0.20.0
trio-websocket==0.9.2
ttkbootstrap @ git+https://github.com/israel-dryer/ttkbootstrap@7d2d803d550d92d16d09ebbf37dcef7582341a9e
ttkthemes==3.2.2
typing_extensions==4.1.1
uncompyle6==3.8.0
unpy2exe==0.4
urllib3==1.26.7
virtualenv==20.14.1
virtualenv-clone==0.5.7
watchdog==2.1.7
wavelink==1.2.5
wcwidth==0.2.5
webdriver-manager==3.5.3
whichcraft==0.6.1
wsproto==1.1.0
xdis==6.0.3
yarl==1.7.2
zope.event==4.5.0
zope.interface==5.4.0

**Comment by MegabotLA** [comment]
Now i have deinstall discord.py and same error 

Starting to load cogs...
Extension activities loaded.
Failed to load extension admin: Extension 'bot.cogs.admin' raised an error: AttributeError: module 'discord.commands.permissions' has no attribute 'has_any_role'

**Comment by Zalatis** [comment]
If you remove the "Admin" cog is there any other errors ?

**Comment by MegabotLA** [comment]
Yes same error in new file :D

Starting to load cogs...
Extension activities loaded.
Extension choix_hebdo loaded.
Extension error loaded.
Extension forum_news loaded.
Extension image loaded.
Extension lfg loaded.
Failed to load extension music: Extension 'bot.cogs.music' raised an error: ImportError: cannot import name 'has_any_role' from 'discord'

**Comment by Zalatis** [comment]
Well there is definitely a problem with py-cord, 
How did you install it ? 

Also I tried to install all your modules from your pip freeze, can't be able to reproduce the problem.

A temporary fix would be maybe to remove all lines containing `@permissions.has_any_role(*PERMITED_ROLES_IDS)`

**Comment by MegabotLA** [comment]
Ok i have removed all lines. 

Starting to load cogs...
Extension activities loaded.
Extension admin loaded.
Extension choix_hebdo loaded.
Extension error loaded.
Extension forum_news loaded.
Extension image loaded.
Extension lfg loaded.
Failed to load extension music: Extension 'bot.cogs.music' raised an error: ImportError: cannot import name 'has_any_role' from 'discord'


Also i removed all lines in Music but this Error still appear

**Comment by MegabotLA** [comment]
ah nvm, i have to remove the import in player.py

now : 

Starting to load cogs...
Extension activities loaded.
Extension admin loaded.
Extension choix_hebdo loaded.
Extension error loaded.
Extension forum_news loaded.
Extension image loaded.
Extension lfg loaded.
Extension music loaded.
Extension news loaded.
Extension reloader loaded.
Extension roles loaded.
Extension tasks loaded.
Completed loading cogs
Running Bot
Closing on keyboard interrupt...
18:19:24 - Bot déconnecté.
Closing connection to Discord...

**Comment by MegabotLA** [comment]
Starting to load cogs...
Extension activities loaded.
Extension admin loaded.
Extension choix_hebdo loaded.
Extension error loaded.
Failed to load extension forum_news: Extension 'bot.cogs.forum_news' raised an error: RuntimeError: Event loop is closed
Failed with {!r}, retrying Extension 'bot.cogs.forum_news' raised an error: RuntimeError: Event loop is closed
C:\Users\Admin\Downloads\LostArkDiscordBot-main\main.py:21: RuntimeWarning: coroutine 'Loop._loop' was never awaited
  print('Failed with {!r}, retrying', e)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Starting to load cogs...
Extension activities loaded.
Extension admin loaded.
Extension choix_hebdo loaded.
Extension error loaded.
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000017E7BB1DB80>
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 746, in call_soon
    self._check_closed()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Failed to load extension forum_news: Extension 'bot.cogs.forum_news' raised an error: RuntimeError: Event loop is closed

**Comment by Zalatis** [comment]
Did you also properly setup every values in config.json ? 
Otherwise we will need to wait for py-cord to update to the permissions v2 system, and will update the bot when is up

**Comment by MegabotLA** [comment]
All edit in config only the Role IDs and Emojis not.

**Comment by Zalatis** [comment]
On my side I can't be able to reproduce your errors, even on a fresh new install.
It may be a problem on your side, you can try to set up the bot in a venv to be sure that nothing else can cause errors

**Comment by Zalatis** [comment]
Nevermind, I found out how to reproduce it, it it because the master branch of py-cord is currently doing updates to support permissions v2

**Comment by Zalatis** [comment]
Do 
`pip uninstall py-cord -y`
`pip install git+https://github.com/Pycord-Development/pycord.git@22d9c92def63d5f65be6dbc64758a5673b830fe3`

It is a temporary fix until I do permissions v2 support
